### ISSUE TITLE
'RuntimeException: isn't a jar URL'  when deployed under Jboss AS 7.3

### ISSUE THREAD

**Issue by miezys** [evrete/evrete#27] opened 2022-10-10 13:43 UTC
Hi,
we are trying to use evrete `2.2.02` (same issue with `2.2.01`) in a java (11) EE application deployed to Jboss AS `7.3` and getting the following exception:

```
Caused by: java.lang.RuntimeException: Unable to open vfs:/content/<ear-file-name>.ear/lib/evrete-core-2.2.02.jar/org/evrete/spi/minimal/ as jar file
	at deployment.<ear-file-name>.ear//org.evrete.util.compiler.PackageExplorer.processJar(PackageExplorer.java:59)
	at deployment.<ear-file-name>.ear//org.evrete.util.compiler.PackageExplorer.listUnder(PackageExplorer.java:28)
	at deployment.<ear-file-name>.ear//org.evrete.util.compiler.PackageExplorer.find(PackageExplorer.java:90)
	at deployment.<ear-file-name>.ear//org.evrete.util.compiler.FileManager.list(FileManager.java:61)
	at jdk.compiler/com.sun.tools.javac.api.ClientCodeWrapper$WrappedJavaFileManager.list(ClientCodeWrapper.java:232)
	at jdk.compiler/com.sun.tools.javac.code.ClassFinder.list(ClassFinder.java:737)
	at jdk.compiler/com.sun.tools.javac.code.ClassFinder.scanUserPaths(ClassFinder.java:674)
	at jdk.compiler/com.sun.tools.javac.code.ClassFinder.fillIn(ClassFinder.java:554)
	at jdk.compiler/com.sun.tools.javac.code.ClassFinder.complete(ClassFinder.java:299)
	at jdk.compiler/com.sun.tools.javac.code.Symbol.complete(Symbol.java:642)
	at jdk.compiler/com.sun.tools.javac.comp.TypeEnter$ImportsPhase.checkClassPackageClash(TypeEnter.java:388)
	at jdk.compiler/com.sun.tools.javac.comp.TypeEnter$ImportsPhase.resolveImports(TypeEnter.java:361)
	at jdk.compiler/com.sun.tools.javac.comp.TypeEnter$ImportsPhase.runPhase(TypeEnter.java:321)
	at jdk.compiler/com.sun.tools.javac.comp.TypeEnter$Phase.doCompleteEnvs(TypeEnter.java:282)
	at jdk.compiler/com.sun.tools.javac.comp.TypeEnter$Phase.completeEnvs(TypeEnter.java:251)
	at jdk.compiler/com.sun.tools.javac.comp.TypeEnter.complete(TypeEnter.java:198)
	at jdk.compiler/com.sun.tools.javac.code.Symbol.complete(Symbol.java:642)
	at jdk.compiler/com.sun.tools.javac.code.Symbol$ClassSymbol.complete(Symbol.java:1326)
	at jdk.compiler/com.sun.tools.javac.comp.Enter.complete(Enter.java:583)
	at jdk.compiler/com.sun.tools.javac.comp.Enter.main(Enter.java:560)
	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.enterTrees(JavaCompiler.java:1066)
	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:937)
	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.lambda$doCall$0(JavacTaskImpl.java:104)
	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.handleExceptions(JavacTaskImpl.java:147)
	... 350 more
Caused by: java.lang.Exception: vfs:/content/<ear-file-name>.ear/lib/evrete-core-2.2.02.jar/org/evrete/spi/minimal/ isn't a jar URL
	at deployment.<ear-file-name>.ear//org.evrete.util.compiler.PackageExplorer.processJar(PackageExplorer.java:39)
	... 373 more
```
We have no issues while using evrete in junit tests, but it does not run when deployed to Jboss. Did we have missed some instructions on how to correctly use evrete? 

P.S. The actual file name in the stacktrace was replaced with `<ear-file-name>`.

**Comment by andbi** [comment] 2022-10-10 17:50
The root cause is that the `File.isDirectory()` method returns false given the `vfs:/content/<ear-file-name>.ear/lib/evrete-core-2.2.02.jar/org/evrete/spi/minimal/` argument. The provided stack trace isn't enough to tell if it's a problem with VFS wrapper or the library's code.  There are several options here:

1. You provide a minimalistic Wildfly configuration with VFS support enabled and a simple project that would reproduce the exception (a web-tier component, an EJB, etc.), and I try to resolve the issue myself.
2. If you know how to build Maven projects, we could fix it together by debugging the `PackageExplorer` class, namely the `listUnder` method.

**Comment by andbi** [comment] 2022-10-11 00:18
@miezys please disregard the last comment, I see he same exception on  wildfly-26.1.2.Final, marking it as a bug.

**Comment by miezys** [comment] 2022-10-11 06:22
> @miezys please disregard the last comment, I see the same exception when running Wildfly-26.1.2.Final.

Thanks a lot for having a look at it :clap: Building and debugging is not a problem, if you need some assistance I will be happy to do so.

**Closed as completed** 2022-10-12 01:28 UTC
Labels: bug

**Comment by andbi** [comment] 2022-10-12 01:45
@miezys please give it a try, version 2.2.03, tested on WildFly-26.1.2.Final, test source [`quickstart-26.1.2.Final/ejb-in-ear`](https://github.com/wildfly/quickstart/tree/26.1.2.Final/ejb-in-ear) with the `org.jboss.as.quickstarts.ear.ejb.GreeterEJB.java` class modified as follows:

```java
@Stateful
public class GreeterEJB {
    Knowledge knowledge;

    public String sayHello(String name) {
        StatelessSession session = knowledge.newStatelessSession();
        StringWrapper wrapper = new StringWrapper(name);
        session.insertAndFire(wrapper);
        return wrapper.getName();
    }

    @PostConstruct
    public void init() {
        KnowledgeService service = new KnowledgeService();
        this.knowledge = service.newKnowledge()
                .newRule()
                .forEach("$s", StringWrapper.class)
                .where("$s.name.length() > 0")
                .execute(ctx->{
                    StringWrapper s = ctx.get("$s");
                    s.setName("Hello " + s.getName() + "!!!!");
                });
    }

    public static class StringWrapper {
        private String name;

        public StringWrapper(String name) {
            this.name = name;
        }

        public String getName() {
            return name;
        }

        public void setName(String name) {
            this.name = name;
        }
    }
}

```

**Comment by miezys** [comment] 2022-10-13 10:44
It is working now fine, thanks a lot @andbi !
